version: '3'

services:
  student_rpc:
    image: nutthaphonsu/student_rpc:1.0
    container_name: student_rpc
    restart: "no"
    
    depends_on:
      - db
    networks:
      - microservice
      - default
      
  db:
    container_name: student_mariadb
    image: mariadb:latest
    restart: "no"
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=devops101
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101
      
networks:
  default:
    external:
      name: student_network
  microservice:
    external:
      name: microservice_network
